import { Outfit } from "next/font/google";
import AOSWrapper from "./AOSwrapper";
import { ClerkProvider } from '@clerk/nextjs'
import "./globals.css";

const inter = Outfit({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (

    <ClerkProvider>
      <html lang="en">
      <body className={inter.className}>
        <AOSWrapper>{children}</AOSWrapper>
      </body>
    </html>
    </ClerkProvider>
    
  );
}
